services:
  rebootx-on-prem:
    image: golang:1.22
    environment:
      # RebootX On-Prem configuration
      - RBTX_API_KEY=${REBOOTX_API_KEY:-tailscale-mcp-rebootx-key-2024}
      - RBTX_PATH_PREFIX=${REBOOTX_PATH_PREFIX:-tailscale-mcp}
      - RBTX_DASHBOARD_SERVICE_FILE_JSON_FILE_PATH=/data/dashboards.json
      - RBTX_DASHBOARD_SERVICE_IMPL=fileJson
      - RBTX_PORT=9001
      - RBTX_RUNNABLE_SERVICE_FILE_JSON_FILE_PATH=/data/servers.json
      - RBTX_RUNNABLE_SERVICE_IMPL=fileJson
      - RBTX_BIND=0.0.0.0
      - RBTX_PROTOCOL=http
    ports:
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./impl:/app
    working_dir: "/app"
    command: bash -c "cd /app/http-server-go && go fmt && go build -o /build/rebootx-on-prem -v && /build/rebootx-on-prem"
    networks:
      - monitoring
    depends_on:
      - tailscale-mcp
      - grafana
      - prometheus
      - loki

  rebootx-swagger-ui:
    image: swaggerapi/swagger-ui:v5.12.0
    environment:
      - PORT=9002
      - SWAGGER_JSON=/spec/swagger.json
    ports:
      - "9002:9002"
    volumes:
      - ./spec:/spec
    networks:
      - monitoring
    depends_on:
      - rebootx-on-prem

networks:
  monitoring:
    external: true
