global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Tailscale MCP Server metrics
  - job_name: 'tailscale-mcp'
    static_configs:
      - targets: ['tailscale-mcp:9091']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Docker container metrics (if node_exporter is added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Tailscale API metrics (if we add a Tailscale exporter)
  - job_name: 'tailscale-exporter'
    static_configs:
      - targets: ['tailscale-exporter:9119']
    scrape_interval: 30s
