name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Ruff formatter
        run: uv run ruff format --check .

      - name: Run MyPy type checker
        run: uv run mypy src/

      - name: Run Pylint
        run: uv run pylint src/

      - name: Check code complexity
        run: uv run flake8 --max-complexity=10 src/

      - name: Check docstring coverage
        run: uv run interrogate src/

  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Check documentation
        run: |
          # Check if all public functions have docstrings
          uv run pydocstyle src/
          
          # Check if README exists and is not empty
          test -s README.md
          
          # Check if CHANGELOG exists
          test -f CHANGELOG.md

      - name: Build documentation
        run: |
          # This would build documentation if we had Sphinx or similar
          echo "Documentation build would go here"

  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run performance tests
        run: |
          uv run pytest tests/ -m performance --benchmark-only --benchmark-save=performance

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: .benchmarks/
